language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

notifications:
  email: false

branches:
  only:
    - master

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION >= v"0.7" && using Pkg; Pkg.clone(pwd()); Pkg.build("OptimizationProblems"); Pkg.test("OptimizationProblems"; coverage=true)'

after_success:
  - julia -e 'VERSION >= v"0.7" && using Pkg; cd(Pkg.dir("OptimizationProblems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
